import "./globals.css";
import "./index.scss";

import { Navbar } from "@/components";

const graphqlAPI = process.env.NEXT_PUBLIC_GRAPHCMS_ENDPOINT 





export const metadata = {
  title: "GraphBlog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg[#050816]   md:px-[7rem] ">
        <div
          // style={{
          //   backgroundImage: "url('/herobg.png')",
          //   width: "100%",
          //   height: "100vh",
          //   backgroundRepeat: "no-repeat",
          //   backgroundSize: "cover",
          // }}
          // className="  bg-cover bg-no-repeat bg-center"
        >
          <main className="app">
            <Navbar />
            
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}


// nextjs way ==?


// Fetch data at build time
// export async function getStaticProps() {
//   const posts = (await getPosts()) || [];
//   return {
//     props: { posts },
//   };
// };


// post are fetching to Page -> postcard